On Error Resume Next
strComputer = "."
Set objWMIService = GetObject("winmgmts:\\" & strComputer & "\root\cimv2")
Set colItems = objWMIService.ExecQuery("Select * from Win32_Printer",,48)
For Each objItem in colItems
    Wscript.Echo "Attributes: " & objItem.Attributes
    Wscript.Echo "Availability: " & objItem.Availability
    Wscript.Echo "AvailableJobSheets: " & objItem.AvailableJobSheets
    Wscript.Echo "AveragePagesPerMinute: " & objItem.AveragePagesPerMinute
    Wscript.Echo "Capabilities: " & objItem.Capabilities
    Wscript.Echo "CapabilityDescriptions: " & objItem.CapabilityDescriptions
    Wscript.Echo "Caption: " & objItem.Caption
    Wscript.Echo "CharSetsSupported: " & objItem.CharSetsSupported
    Wscript.Echo "Comment: " & objItem.Comment
    Wscript.Echo "ConfigManagerErrorCode: " & objItem.ConfigManagerErrorCode
    Wscript.Echo "ConfigManagerUserConfig: " & objItem.ConfigManagerUserConfig
    Wscript.Echo "CreationClassName: " & objItem.CreationClassName
    Wscript.Echo "CurrentCapabilities: " & objItem.CurrentCapabilities
    Wscript.Echo "CurrentCharSet: " & objItem.CurrentCharSet
    Wscript.Echo "CurrentLanguage: " & objItem.CurrentLanguage
    Wscript.Echo "CurrentMimeType: " & objItem.CurrentMimeType
    Wscript.Echo "CurrentNaturalLanguage: " & objItem.CurrentNaturalLanguage
    Wscript.Echo "CurrentPaperType: " & objItem.CurrentPaperType
    Wscript.Echo "Default: " & objItem.Default
    Wscript.Echo "DefaultCapabilities: " & objItem.DefaultCapabilities
    Wscript.Echo "DefaultCopies: " & objItem.DefaultCopies
    Wscript.Echo "DefaultLanguage: " & objItem.DefaultLanguage
    Wscript.Echo "DefaultMimeType: " & objItem.DefaultMimeType
    Wscript.Echo "DefaultNumberUp: " & objItem.DefaultNumberUp
    Wscript.Echo "DefaultPaperType: " & objItem.DefaultPaperType
    Wscript.Echo "DefaultPriority: " & objItem.DefaultPriority
    Wscript.Echo "Description: " & objItem.Description
    Wscript.Echo "DetectedErrorState: " & objItem.DetectedErrorState
    Wscript.Echo "DeviceID: " & objItem.DeviceID
    Wscript.Echo "Direct: " & objItem.Direct
    Wscript.Echo "DoCompleteFirst: " & objItem.DoCompleteFirst
    Wscript.Echo "DriverName: " & objItem.DriverName
    Wscript.Echo "EnableBIDI: " & objItem.EnableBIDI
    Wscript.Echo "EnableDevQueryPrint: " & objItem.EnableDevQueryPrint
    Wscript.Echo "ErrorCleared: " & objItem.ErrorCleared
    Wscript.Echo "ErrorDescription: " & objItem.ErrorDescription
    Wscript.Echo "ErrorInformation: " & objItem.ErrorInformation
    Wscript.Echo "ExtendedDetectedErrorState: " & objItem.ExtendedDetectedErrorState
    Wscript.Echo "ExtendedPrinterStatus: " & objItem.ExtendedPrinterStatus
    Wscript.Echo "Hidden: " & objItem.Hidden
    Wscript.Echo "HorizontalResolution: " & objItem.HorizontalResolution
    Wscript.Echo "InstallDate: " & objItem.InstallDate
    Wscript.Echo "JobCountSinceLastReset: " & objItem.JobCountSinceLastReset
    Wscript.Echo "KeepPrintedJobs: " & objItem.KeepPrintedJobs
    Wscript.Echo "LanguagesSupported: " & objItem.LanguagesSupported
    Wscript.Echo "LastErrorCode: " & objItem.LastErrorCode
    Wscript.Echo "Local: " & objItem.Local
    Wscript.Echo "Location: " & objItem.Location
    Wscript.Echo "MarkingTechnology: " & objItem.MarkingTechnology
    Wscript.Echo "MaxCopies: " & objItem.MaxCopies
    Wscript.Echo "MaxNumberUp: " & objItem.MaxNumberUp
    Wscript.Echo "MaxSizeSupported: " & objItem.MaxSizeSupported
    Wscript.Echo "MimeTypesSupported: " & objItem.MimeTypesSupported
    Wscript.Echo "Name: " & objItem.Name
    Wscript.Echo "NaturalLanguagesSupported: " & objItem.NaturalLanguagesSupported
    Wscript.Echo "Network: " & objItem.Network
    Wscript.Echo "PaperSizesSupported: " & objItem.PaperSizesSupported
    Wscript.Echo "PaperTypesAvailable: " & objItem.PaperTypesAvailable
    Wscript.Echo "Parameters: " & objItem.Parameters
    Wscript.Echo "PNPDeviceID: " & objItem.PNPDeviceID
    Wscript.Echo "PortName: " & objItem.PortName
    Wscript.Echo "PowerManagementCapabilities: " & objItem.PowerManagementCapabilities
    Wscript.Echo "PowerManagementSupported: " & objItem.PowerManagementSupported
    Wscript.Echo "PrinterPaperNames: " & objItem.PrinterPaperNames
    Wscript.Echo "PrinterState: " & objItem.PrinterState
    Wscript.Echo "PrinterStatus: " & objItem.PrinterStatus
    Wscript.Echo "PrintJobDataType: " & objItem.PrintJobDataType
    Wscript.Echo "PrintProcessor: " & objItem.PrintProcessor
    Wscript.Echo "Priority: " & objItem.Priority
    Wscript.Echo "Published: " & objItem.Published
    Wscript.Echo "Queued: " & objItem.Queued
    Wscript.Echo "RawOnly: " & objItem.RawOnly
    Wscript.Echo "SeparatorFile: " & objItem.SeparatorFile
    Wscript.Echo "ServerName: " & objItem.ServerName
    Wscript.Echo "Shared: " & objItem.Shared
    Wscript.Echo "ShareName: " & objItem.ShareName
    Wscript.Echo "SpoolEnabled: " & objItem.SpoolEnabled
    Wscript.Echo "StartTime: " & objItem.StartTime
    Wscript.Echo "Status: " & objItem.Status
    Wscript.Echo "StatusInfo: " & objItem.StatusInfo
    Wscript.Echo "SystemCreationClassName: " & objItem.SystemCreationClassName
    Wscript.Echo "SystemName: " & objItem.SystemName
    Wscript.Echo "TimeOfLastReset: " & objItem.TimeOfLastReset
    Wscript.Echo "UntilTime: " & objItem.UntilTime
    Wscript.Echo "VerticalResolution: " & objItem.VerticalResolution
    Wscript.Echo "WorkOffline: " & objItem.WorkOffline
Next

